future: true
permalink: /:title/
url: http://JocelynWSJ.github.io
name: Jocelyn Wang
author: Sir Pan
qq: 809984476
email: wangshj9@mail2.sysu.edu.cn

duoshuo: JocelynW
beian: 
cnzz: 
weibo: 
github: JocelynWSJ
about: "这里是 JocelynW 的个人博客，创建于 2018 年。"

safe: true
paginate: 20

theme: jekyll-theme-merlot
