/* Rider–Waite–Smith card names and concise traditional interpretations. */
const suitData = {
  Wands: [
    ['Ace of Wands','spark, inspiration, a bold beginning','delay, exhaustion, a false start'],['Two of Wands','planning, possibility, choosing a horizon','fear of the unknown, limited planning'],['Three of Wands','expansion, foresight, momentum','obstacles, waiting, a scattered direction'],['Four of Wands','celebration, homecoming, belonging','instability, tension at home'],['Five of Wands','healthy friction, competition, testing ideas','avoiding conflict, unresolved tension'],['Six of Wands','recognition, confidence, a visible win','self-doubt, private success, delayed praise'],['Seven of Wands','conviction, boundaries, holding your ground','overwhelm, giving up too soon'],['Eight of Wands','swift movement, news, alignment','delays, miscommunication, resistance'],['Nine of Wands','resilience, persistence, earned caution','fatigue, defensiveness, depleted reserves'],['Ten of Wands','responsibility, effort, a full load','release, delegation, reassessing burdens'],['Page of Wands','curiosity, a creative message, exploration','hesitation, scattered energy, disappointing news'],['Knight of Wands','adventure, courage, spirited action','impulsiveness, frustration, reckless action'],['Queen of Wands','warmth, confidence, magnetic creativity','insecurity, jealousy, dimmed confidence'],['King of Wands','vision, leadership, generous ambition','forcefulness, impatience, unrealistic aims']
  ],
  Cups: [
    ['Ace of Cups','open-heartedness, new feeling, emotional renewal','emotional blockage, emptiness, withheld feeling'],['Two of Cups','connection, mutuality, a meaningful union','imbalance, separation, miscommunication'],['Three of Cups','friendship, joy, shared abundance','isolation, overindulgence, social strain'],['Four of Cups','contemplation, reevaluation, an overlooked offer','apathy, withdrawal, renewed interest'],['Five of Cups','grief, disappointment, honoring a loss','acceptance, recovery, finding what remains'],['Six of Cups','nostalgia, kindness, simple pleasure','being stuck in the past, unrealistic sentiment'],['Seven of Cups','imagination, choices, possibility','clarity, decisive choice, illusion lifting'],['Eight of Cups','leaving what no longer nourishes, seeking depth','avoidance, fear of change, aimless drifting'],['Nine of Cups','contentment, gratitude, a wish fulfilled','dissatisfaction, excess, superficial pleasure'],['Ten of Cups','harmony, love, shared happiness','misalignment, broken communication, strained ideals'],['Page of Cups','intuition, tender news, creative surprise','emotional immaturity, insecurity, blocked intuition'],['Knight of Cups','romance, imagination, an invitation','moodiness, fantasy without action, disappointment'],['Queen of Cups','compassion, intuition, emotional intelligence','overwhelm, blurred boundaries, self-neglect'],['King of Cups','calm mastery, diplomacy, steady care','emotional manipulation, suppression, volatility']
  ],
  Swords: [
    ['Ace of Swords','clarity, truth, a decisive breakthrough','confusion, harshness, clouded judgment'],['Two of Swords','pause, difficult balance, a guarded choice','indecision, information overload, emotional release'],['Three of Swords','heartbreak, necessary truth, grief','recovery, forgiveness, pain easing'],['Four of Swords','rest, restoration, quiet reflection','burnout, restlessness, returning to activity'],['Five of Swords','conflict, a costly win, competing needs','reconciliation, learning from loss, resentment'],['Six of Swords','transition, healing, moving toward calmer waters','resistance to change, unfinished business'],['Seven of Swords','strategy, independence, moving carefully','self-deception, exposure, making amends'],['Eight of Swords','restriction, fear, a limiting story','release, perspective, reclaimed agency'],['Nine of Swords','anxiety, worry, confronting a shadow','relief, hope, support after struggle'],['Ten of Swords','an ending, surrender, final clarity','recovery, resisting an inevitable ending'],['Page of Swords','curiosity, alertness, a new idea','gossip, defensiveness, scattered thinking'],['Knight of Swords','direct action, conviction, momentum','recklessness, aggression, acting without care'],['Queen of Swords','discernment, independence, clear boundaries','bitterness, coldness, overly critical thought'],['King of Swords','reason, integrity, fair leadership','rigidity, misuse of authority, detached judgment']
  ],
  Pentacles: [
    ['Ace of Pentacles','opportunity, grounding, a tangible seed','missed chance, scarcity, poor planning'],['Two of Pentacles','adaptability, priorities, an active balance','overcommitment, disorganization, imbalance'],['Three of Pentacles','craft, teamwork, building something real','lack of quality, isolation, misaligned effort'],['Four of Pentacles','security, conservation, protecting resources','possessiveness, fear, letting go'],['Five of Pentacles','hardship, exclusion, asking for help','recovery, support, improving conditions'],['Six of Pentacles','generosity, reciprocity, fair exchange','strings attached, debt, unequal giving'],['Seven of Pentacles','patience, assessment, long-term cultivation','impatience, lack of reward, reconsidering investment'],['Eight of Pentacles','practice, diligence, refining a skill','perfectionism, boredom, lack of focus'],['Nine of Pentacles','self-reliance, comfort, earned abundance','dependence, overwork, unstable foundations'],['Ten of Pentacles','legacy, stability, lasting prosperity','family pressure, instability, short-term thinking'],['Page of Pentacles','study, a practical offer, steady potential','procrastination, impracticality, missed learning'],['Knight of Pentacles','reliability, routine, patient progress','stagnation, stubbornness, lack of motivation'],['Queen of Pentacles','nurturing abundance, resourcefulness, home','self-neglect, imbalance, financial worry'],['King of Pentacles','stewardship, security, material wisdom','greed, rigidity, status over values']
  ]
};
const majorData = [
 ['The Fool','0','beginnings, trust, open possibility','recklessness, naivety, a leap without care'],['The Magician','I','willpower, skill, making things happen','manipulation, scattered energy, unused talent'],['The High Priestess','II','intuition, mystery, inner knowing','secrets, disconnection, ignoring intuition'],['The Empress','III','nurture, abundance, creative growth','creative block, dependence, smothering care'],['The Emperor','IV','structure, authority, stability','rigidity, control, inflexibility'],['The Hierophant','V','tradition, learning, shared values','rebellion, limiting beliefs, unconventional path'],['The Lovers','VI','alignment, devotion, an important choice','disharmony, misalignment, conflicting values'],['The Chariot','VII','determination, direction, victory','force without direction, loss of control'],['Strength','VIII','courage, compassion, quiet influence','self-doubt, raw emotion, diminished confidence'],['The Hermit','IX','solitude, guidance, searching within','isolation, withdrawal, lost direction'],['Wheel of Fortune','X','change, cycles, turning point','resistance, bad timing, repeating a pattern'],['Justice','XI','truth, accountability, fair consequence','avoidance, unfairness, lack of responsibility'],['The Hanged Man','XII','pause, surrender, a new perspective','stalling, needless sacrifice, resistance'],['Death','XIII','ending, release, profound transformation','holding on, stagnation, fear of change'],['Temperance','XIV','balance, integration, healing','excess, imbalance, impatience'],['The Devil','XV','attachment, shadow, material entanglement','release, awareness, reclaiming power'],['The Tower','XVI','revelation, disruption, necessary change','avoiding disaster, fear of upheaval'],['The Star','XVII','hope, renewal, clear faith','discouragement, disconnection, lack of trust'],['The Moon','XVIII','intuition, uncertainty, hidden currents','confusion clearing, fear easing, truth emerging'],['The Sun','XIX','joy, vitality, illumination','temporary gloom, unrealistic optimism, delay'],['Judgement','XX','awakening, reckoning, answering a call','self-doubt, avoidance, harsh self-judgment'],['The World','XXI','completion, integration, fulfillment','unfinished business, delay, lack of closure']
];
const slug = s => s.replace(/ /g,'_');
const majorZh=['愚人','魔术师','女祭司','皇后','皇帝','教皇','恋人','战车','力量','隐士','命运之轮','正义','倒吊人','死神','节制','恶魔','高塔','星星','月亮','太阳','审判','世界'];
const suitZh={Wands:'权杖',Cups:'圣杯',Swords:'宝剑',Pentacles:'星币'};
const rankZh={Ace:'王牌',Two:'二',Three:'三',Four:'四',Five:'五',Six:'六',Seven:'七',Eight:'八',Nine:'九',Ten:'十',Page:'侍从',Knight:'骑士',Queen:'皇后',King:'国王'};
const localImage = key => `assets/cards/${key}.jpg`;
const cards = majorData.map((d,i)=>({name:d[0],zhName:majorZh[i],number:d[1],arcana:'Major Arcana',upright:d[2],reversed:d[3],image:localImage(`m${String(i).padStart(2,'0')}`)}));
Object.entries(suitData).forEach(([suit, items]) => items.forEach((d,i) => { const number=String(i+1).padStart(2,'0'), rank=d[0].split(' ')[0], prefix={Wands:'w',Cups:'c',Swords:'s',Pentacles:'p'}[suit]; cards.push({name:d[0],zhName:`${rankZh[rank]}${suitZh[suit]}`,number:'',arcana:suit,upright:d[1],reversed:d[2],image:localImage(`${prefix}${number}`)}); }));
const majorMeaningsZh=[
 ['新的开始、信任与冒险','鲁莽、天真或准备不足'],['意志、技巧与创造','操控、分心或才能未用'],['直觉、神秘与内在智慧','隐秘、疏离或忽视直觉'],['滋养、丰盛与创造力','创造受阻、依赖或过度照顾'],['结构、权威与稳定','僵化、控制或缺少弹性'],['传统、学习与共同价值','反叛、信念受限或另辟路径'],['契合、投入与重要选择','不和、价值冲突或关系失衡'],['决心、方向与胜利','失控、强迫前进或方向模糊'],['勇气、慈悲与温柔的力量','自我怀疑、情绪失控或信心减弱'],['独处、引导与向内寻找','孤立、退缩或迷失方向'],['变化、循环与转折','抗拒改变、时机不佳或旧模式重演'],['真相、责任与公平结果','逃避责任、不公或偏见'],['暂停、臣服与新视角','停滞、无谓牺牲或抗拒'],['结束、释放与深层转化','执着不放、停滞或害怕改变'],['平衡、整合与疗愈','过度、失衡或缺乏耐心'],['束缚、阴影与物质执念','觉察、释放与重获力量'],['突变、揭示与必要的改变','逃避动荡或害怕崩解'],['希望、更新与清澈的信念','灰心、疏离或失去信任'],['直觉、不确定与隐秘流动','迷雾散去、恐惧缓解或真相浮现'],['喜悦、活力与光明','短暂低潮、不切实际的乐观或延迟'],['觉醒、清算与回应召唤','自我怀疑、逃避或严苛批判自己'],['完成、整合与圆满','未竟之事、延迟或缺乏收尾']
];
const rankMeaningsZh={
 Ace:['新的开始与机会','机会受阻或能量不稳'],Two:['平衡、选择与协作','失衡、犹豫或难以取舍'],Three:['成长、合作与初步成果','缺乏配合、受挫或方向不一'],Four:['稳定、庆祝与建立基础','不稳、停滞或害怕失去'],Five:['冲突、考验与面对缺口','回避冲突、接受与恢复'],Six:['进展、互惠与向前移动','延迟、失衡或难以放下'],Seven:['评估、坚持与多重选择','急躁、困惑或缺乏方向'],Eight:['专注、行动与精进','拖延、受困或缺乏专注'],Nine:['韧性、满足与阶段收获','疲惫、不满足或依赖'],Ten:['完成、责任与阶段终点','释放、复原或抗拒结束'],Page:['好奇、新消息与学习','不成熟、犹豫或信息受阻'],Knight:['行动、追求与推进','冲动、停滞或鲁莽前行'],Queen:['自信、成熟与直觉照料','不安、情绪失衡或自我忽略'],King:['掌控、领导与成熟判断','固执、控制或权力失衡']
};
const suitFocusZh={Wands:'行动、创意与意志',Cups:'情感、直觉与关系',Swords:'思想、沟通与抉择',Pentacles:'现实、资源与长期基础'};
cards.forEach((card,i)=>{if(i<22){[card.uprightZh,card.reversedZh]=majorMeaningsZh[i]}else{const rank=card.name.split(' ')[0],meaning=rankMeaningsZh[rank];card.uprightZh=`${meaning[0]}；聚焦于${suitFocusZh[card.arcana]}。`;card.reversedZh=`${meaning[1]}；留意${suitFocusZh[card.arcana]}中的课题。`}});
window.TAROT_CARDS = cards;
